---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rca-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yb-rca
  labels:
    app: yb-rca
  namespace: opni-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yb-rca
  template:
    metadata:
      labels:
        app: yb-rca
    spec:
      volumes:
        - name: rca-pvc-mount
          persistentVolumeClaim:
            claimName: rca-pvc
      containers:
      - name: yb-rca
        env:
        - name: DATA_DIR
          value: "/data"
        - name: OPENSEARCH_URL
          value: https://opni-os-svc.opni-system.svc:9200
        volumeMounts:
          - mountPath: /data
            name: rca-pvc-mount
        image: docker.io/tybalex/opni-rca:mc
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
      - name: yb-rca-trainer
        env:
        - name: DATA_DIR
          value: "/data"
        - name: OPENSEARCH_URL
          value: https://opni-os-svc.opni-system.svc:9200
        volumeMounts:
          - mountPath: /data
            name: rca-pvc-mount
        image: docker.io/tybalex/opni-rca_trainer:mc
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: yb-rca-service
  namespace: opni-system
spec:
  ports:
  - name: http
    port: 5050
    targetPort: 5050
  selector:
    app: yb-rca
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yb-rca-service-external
  namespace: opni-system
spec:
  ports:
  - name: http
    port: 5050
    targetPort: 5050
  selector:
    app: yb-rca
  type: LoadBalancer
